### PR TITLE
fix: Titlebar text being off + Sidebar style improvement

### PR DESCRIPTION
**Pull request by Lythium4848**
fixed the titlebar text being off by 2 pixels because MrPresident in gmodstore discord was complaining

### CODE REVIEW

**Comment by Lythium4848** [comment]
fuck it put the other commits in

**Comment by FelixKLG** [comment]
10 out of 10, Lythium is the sussyest of bakas and it poggers amazing.

**Comment by Lythium4848** [comment]
shut the fuck up felix

**Review by LucaTanks — APPROVED** [review]

**Review by LucaTanks — APPROVED** [review]

**Comment by Lythium4848** [comment]
accept my pull request

**Review by garryspins — APPROVED** [review]

**Comment by TomDotBat** [comment]
accepted.

**Comment by Lythium4848** [comment]
you spacker

**Comment by FelixKLG** [comment]
lmao
I think you're supposed to close & merge when sayig 'accepted'.

**Comment by LucaTanks** [comment]
[LucaTanks](https://github.com/LucaTanks) approved these changes

**Comment by TomDotBat** [comment]
disaccepted

**Comment by FelixKLG** [comment]
lmao mong.
return to your filthy JIT language.

**Comment by garryspins** [comment]
youre retarded felix

**Comment by FelixKLG** [comment]
And you're American Melon, it shows.

Also you missed out a large portion of the grammer in your prior message.

**Comment by garryspins** [comment]
shush reratd

**Pull request closed without merging**
